package th.vv3.controller.v1;

import io.swagger.annotations.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import th.vv3.models.Customer;
import th.vv3.repositories.CustomerRepository;

import java.util.Optional;
import java.util.UUID;

@Api(tags = "Customer", description = "Get, Create, Change and Delete Customers")
@RestController
@RequestMapping("api/v1/customers")
public class CustomersController {
    private CustomerRepository customerRepository;

    public CustomersController(@Autowired CustomerRepository customerRepository) {
        this.customerRepository = customerRepository;
    }

    @GetMapping
    @ApiOperation( // SWAGGER
            value = "Returns all Customers",
            notes = "...",
            response = Customer.class,
            produces = "application/json")
    @ApiResponses(value = { // SWAGGER
            @ApiResponse(code = 200, response = Customer.class, message = "Returned all customers", responseContainer = "List"),
            @ApiResponse(code = 400, message = "Bad Request"),})
    public ResponseEntity getAll() {
        return new ResponseEntity<>(this.customerRepository.findAll(), HttpStatus.OK);
    }

    @GetMapping("{customerId}")
    @ApiOperation( // SWAGGER
            value = "Searches customer with ID",
            notes = "...",
            response = Customer.class,
            produces = "application/json")
    @ApiResponses(value = { // SWAGGER
            @ApiResponse(code = 200, message = "Customer found"),
            @ApiResponse(code = 400, message = "Bad Request"),
            @ApiResponse(code = 404, message = "Customer not found"),})
    public ResponseEntity getCustomerById(@ApiParam(value = "Unique Id of the Customer", required = true) @PathVariable UUID customerId) {
        Optional<Customer> customer = customerRepository.findById(customerId);
        if (customer.isEmpty()) {
            return new ResponseEntity<>("not found", HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<>(customer.get(), HttpStatus.OK);
    }

    @PostMapping
    @ApiOperation( // SWAGGER
            value = "Creates a Customer",
            response = Customer.class,
            produces = "application/json")
    @ApiResponses(value = { // SWAGGER
            @ApiResponse(code = 201, message = "Customer created"),
            @ApiResponse(code = 400, message = "Bad Request"),
            @ApiResponse(code = 409, message = "Email already used or Id already used"),})
    public ResponseEntity create(@ApiParam(value = "New Customer that should be created. If CustomerId is not set it will autogenerated", required = true) @RequestBody Customer customer) {
        if (customer.getCustomerId() == null) {
            customer.setCustomerId(UUID.randomUUID());
        }
        try {
            customerRepository.save(customer);
        } catch (DataIntegrityViolationException e) {
            return new ResponseEntity<>(e.getMessage(), HttpStatus.CONFLICT);
        }
        return new ResponseEntity<>(customer, HttpStatus.CREATED);
    }

    @PutMapping("{customerId}")
    @ApiOperation( // SWAGGER
            value = "Change a Customer",
            response = Customer.class,
            produces = "application/json")
    @ApiResponses(value = { // SWAGGER
            @ApiResponse(code = 200, message = "Customer changed"),
            @ApiResponse(code = 400, message = "Bad Request"),
            @ApiResponse(code = 404, message = "Customer not found"),})
    public ResponseEntity change(@ApiParam(value = "Customer changes", required = true) @RequestBody Customer customer,
                                 @ApiParam(value = "Unique Id of the changing Customer", required = true) @PathVariable UUID customerId) {
        if (customerRepository.findById(customerId).equals(Optional.empty())) {
            return new ResponseEntity<>("not found", HttpStatus.NOT_FOUND);
        }

        try {
            customer.setCustomerId(customerId);
            customer = customerRepository.saveAndFlush(customer);
        } catch (Exception e) {
            return new ResponseEntity<>("version is outdated", HttpStatus.BAD_REQUEST);
        }
        return new ResponseEntity<>(customer, HttpStatus.OK);
    }

    @DeleteMapping("{customerId}")
    @ApiOperation( // SWAGGER
            value = "Deletes customer with ID",
            notes = "...")
    @ApiResponses(value = { // SWAGGER
            @ApiResponse(code = 200, message = "Customer deleted"),
            @ApiResponse(code = 400, message = "Bad Request"),
            @ApiResponse(code = 404, message = "Customer not found"),})
    public ResponseEntity delete(@ApiParam(value = "Unique Id of the deleting Customer", required = true)@PathVariable UUID customerId) {
        Optional<Customer> customer = customerRepository.findById(customerId);

        if (customer.isEmpty()) {
            return new ResponseEntity<>("customer does not exist", HttpStatus.NOT_FOUND);
        }

        customerRepository.delete(customer.get());
        return new ResponseEntity<>("customer deleted", HttpStatus.OK);
    }
}
