stages:
  - build
  - execute


build:
  image: gradle:6.3.0-jdk14
  stage: build
  script: cd src/main/java && javac domain/services/*.java domain/models/*.java
  artifacts:
    untracked: true
#
#execute:
#  image: gradle:6.3.0-jdk14
#  stage: execute
#  script: cd src/main/java && java domain.services.DirectoryWatcher
