stages:
  - build
  - execute


build:
  image: java:latest
  stage: build
  script: cd Domain && javac Services/*.java
  artifacts:
    untracked: true

execute:
  image: java:latest
  stage: execute
  script: cd Domain && java Services/WatchedFile
