stages:
  - build
  - execute


build:
  image: java:14
  stage: build
  script: cd src/main/java && javac Domain/Services/*.java
  artifacts:
    untracked: true

execute:
  image: java:14
  stage: execute
  script: cd src/main/java && java Domain.Services.WatchedFile
