stages:
  - build
  - test

image: gradle:6.3.0-jdk14

#build:
#  stage: build
#  script:
#    - cd erstesProjektVV
#    - gradle assemble
#
#test:
#  stage: test
#  script:
#   - cd erstesProjektVV
#   - gradle test

# build:
#   stage: build
#   script:
#     - cd messaging/CustomerService
#     - gradle assemble

#     - cd ../AccountingService
#     - gradle assemble

#     - cd ../TeamLead
#     - gradle assemble

#     - cd ../Common
#     - gradle assemble

test:
  stage: test
  script:
    # - cd messaging/CustomerService
    # - gradle test

    - cd messaging/AccountingService
    - gradle test
    - ls build/test-results/test

    # - cd ../TeamLead
    # - gradle test
    # - cd ../Common
    # - gradle test
    # - cd ..

  artifacts:
    reports:
      junit: messaging/AccountingService/build/test-results/test/TEST-*.xml
